services:

  backend:
    build:
      context: ./taiyaki-backend
      dockerfile: Dockerfile
    container_name: taiyaki_backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:mysql://localhost:3306/taiyaki_database"
      DB_USERNAME: taiyaki_user
      DB_PASSWORD: taiyaki_password
      JWT_SECRET: your_jwt_secret_key
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0 -XX:+UseContainerSupport"
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: taiyaki_database
      MYSQL_USER: taiyaki_user
      MYSQL_PASSWORD: taiyaki_password
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql

volumes:
    mysql_data: